CONFIG_LOG=y
CONFIG_PRINTK=y

# Radar协议一次性调用/打印较多，给主线程多一些栈
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_ASYNC_API=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_GPIO=y
CONFIG_DMA=y

CONFIG_SERIAL=y

# console
CONFIG_CONSOLE=y
